### ISSUE TITLE
standardized header

### ISSUE THREAD

**Issue by Eluinhost** [Eluinhost/Match-Calendar#1]
Use a link within the post to 'hide' data in the post itself

Format:

``` markdown
[{
  open: 'ISO8601 String',
  white: 'ISO8601 String',
  title: 'String',
  address: 'String'
}](/matchpost)
```

Requires CSS like this:

``` css
a[href$="/matchpost"] {  
    display:none
} 
```

Need a generator that can generate these 'headers' people can place in the post self text so we can parse them on the calendar
